ontoportal-lirmm/ontologies_api

- Gemfile
- Gemfile.lock
- controllers/ontology_submissions_controller.rb
- helpers/application_helper.rb
- helpers/request_params_helper.rb
- helpers/submission_helper.rb
- test/controllers/test_ontology_submissions_controller.rb
- https://github.com/ontoportal-lirmm/goo/pull/33
- https://github.com/ontoportal-lirmm/goo/pull/34
https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217
- Paginate the `/submissions` endpoint if the request parameter `page` is present (https://github.com/ontoportal-lirmm/ontologies_api/pull/34/commits/ab8c876b036f8db95848e79981561f759efa6e93)
- Implement `naturalLanguage`, `hasOntologyLanguage_acronym`, `ontology_hasDomain_acronym`, `ontology_group_acronym`, `ontology_name`, `isOfType`, `viewingRestriction`, `status`, `submissionStatus` filters for the `/submissions` endpoint (https://github.com/ontoportal-lirmm/ontologies_api/pull/34/commits/f1b1234644f394fa902730df82180114f6e1996c)
> Feature: Implement pagination and filters to submissions endpoint

- Gemfile
- Gemfile.lock
- helpers/application_helper.rb
- test/controllers/test_ontologies_controller.rb
Resolves https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/89 
- Fix `populate_from_params` help to reset object attributes to empty (https://github.com/ontoportal-lirmm/ontologies_api/commit/7658a15eca81418b30b9c083bbf9011c61ea5c55)
> Fix: detaching views from ontology

- controllers/classes_controller.rb
- helpers/classes_helper.rb
- test/controllers/test_schemes_controller.rb
fix https://github.com/ontoportal-lirmm/ontologies_api/issues/49
> Fix: isInActiveScheme attribute in the class/tree endpoint 

- helpers/submission_helper.rb
Follow up of https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/104
To fix this display of all attributes of metrics object in the submission endpoint
From 
To
> Fix: include all metrics attribues in the submissions endpoints

- helpers/request_params_helper.rb
- test/controllers/test_ontology_submissions_controller.rb
This PR, adds a unit test for the submission endpoint for the status filter. 
And use direct filtering for the status (alpha, beta, production) instead of inverse clauses
> Fix: ontology submissions filter by status retired 

- Gemfile
- Gemfile.lock
- test/controllers/test_agents_controller.rb
* https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/109
> Feature: add agent usage attribute tests

- Gemfile.lock
- controllers/analytics_controller.rb
- helpers/application_helper.rb
- test/controllers/test_annotator_controller.rb
- test/controllers/test_mappings_controller.rb
- test/controllers/test_ontology_analytics_controller.rb
* https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/118
* Add `/data/analytics/ontologies` endpoint, to get ontologies visits evolution by time.
* Add `/data/analytics/users` endpoint, to get users visits   evolution by time. 
* Add `/data/analytics/page_visits` endpoint, to get top pages visited in the current month.
> Feature: add analytics controller with  endpoints for users, ontologies and pages

- Gemfile
- Gemfile.lock
- controllers/admin_controller.rb
- controllers/search_controller.rb
- docker-compose.yml
- test/controllers/test_agents_controller.rb
- test/controllers/test_search_controller.rb
- test/controllers/test_search_models_controller.rb
- test/test_case.rb
* https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/130 
* Add search administration endpoints to init schema and index batch (https://github.com/ontoportal-lirmm/ontologies_api/pull/70/commits/5f319b7865b0dd518f7be2bdd9ff6de196f96325)
* Add admin search in collections (https://github.com/ontoportal-lirmm/ontologies_api/pull/70/commits/f156cdc358128992164c6b8144f3cf80e1529c22)
* Make the search admin use directly the solr connector (https://github.com/ontoportal-lirmm/ontologies_api/pull/70/commits/e33a97b6c12b1dadc66ecde3420a51fb7c776587)
* Add ontology and agent search endpoints (https://github.com/ontoportal-lirmm/ontologies_api/pull/70/commits/1fb990d878fac7e3486452722e92ff88d641de1b)
* Add agent and ontology search tests …
> Feature: Search administration & Ontology and Agents search 

- controllers/search_controller.rb
- test/controllers/test_search_models_controller.rb
* Add ontology accessibility restriction to ontology metadata search (https://github.com/ontoportal-lirmm/ontologies_api/commit/6a4de67c32922e819ec76306d370227a2f5c3a7c)
* Add ontology accessibility restriction to ontology content search (https://github.com/ontoportal-lirmm/ontologies_api/commit/486748a8579d6305daf7b35215e63cd85de6e445)
* Add search results accessibility security test (https://github.com/ontoportal-lirmm/ontologies_api/commit/7504a63109d365531a007666a0d333200f09c49c)
> Feature: Add accessibility security to ontology metadata & content search results 

- controllers/mappings_controller.rb
- test/controllers/test_mappings_controller.rb
- test/helpers/test_slices_helper.rb
- Made the endpoint `/mappings/statistics/ontologies/` supports slices (when we call it from a slice then limit the ontologies only to the ontologies of this slice)
- Add a test for that
> Feature: mappings statistics slices support

- Gemfile.lock
- helpers/search_helper.rb
- test/controllers/test_search_models_controller.rb
Fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/612  which is returning an error because after the annotation fetched we populate them with the index data, but as the result are too big, we overfow the limit of what an URL get request can have. We can this error in the API logs 
This PR fix that  by using `submit_search_query` to call SOLR using POST not GET (https://github.com/ontoportal-lirmm/ontologies_api/commit/2b9503a92f876d8b461baa235008a3e0bf39fa6d)
> Fix: Annotator request size limit 

- controllers/agents_controller.rb
Related issue:
https://github.com/agroportal/project-management/issues/471
Related GOO PR:
https://github.com/ontoportal-lirmm/goo/pull/62
> Fix: remove duplicated agents root

- Gemfile.lock
- controllers/agents_controller.rb
- test/controllers/test_ontologies_controller.rb
* https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/145
* Implement ontology agents endpoint (https://github.com/ontoportal-lirmm/ontologies_api/commit/68fcdf6b54e630025953d00bffe757b7b345d25f) to fix https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/123
> Feature: implement ontology agents endpoint

- controllers/search_controller.rb
- helpers/search_helper.rb
- test/controllers/test_annotator_controller.rb
- test/controllers/test_search_controller.rb
* fix  https://github.com/ontoportal/ontoportal-project/issues/56
* fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/577
> Fix: Search multilingual values filter 

- controllers/search_controller.rb
When we search for example for the query = abcdefghijklmnopqrstuvwxyz 
we get 36 agents (https://data.stageportal.lirmm.fr/search/agents?query=abcdefghijklmnopqrstuvwxyz)
and the expected behavior is to get no agent
Changed the search query logic passed to Solr to make it match only Strings and substrings rather than individual letters
> Fix: Agents search sensibility

- Gemfile
- Gemfile.lock
- config/environments/config.rb.sample
- controllers/home_controller.rb
- controllers/properties_controller.rb
- docker-compose.yml
- test/controllers/test_properties_controller.rb
* https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/155
fix https://github.com/agroportal/project-management/issues/592, by adding to the root endpoint, the portal configuration information, set in the configuration files. See an example bellow 
```json 
{
"acronym": "bioportal",
"title": "NCBO BioPortal",
"color": "#234979",
"description": "The world's most comprehensive repository of biomedical ontologies ",
"logo": "",
"numberOfArtefacts": 1,
"federated_portals": {
"agroportal": {
"api": "http://data.agroportal.lirmm.fr",
"ui": "http://agroportal.lirmm.fr",
"color": "#1e2251"
},
"bioportal": {
"api": "http://data.bioontology.org",
"ui": "http://bioportal.bioontology.org",
"color": "#234979"
}
},
"fundedBy": [
{
"img_src": …
```
> Feature: update home endpoint to add portal config information

- Gemfile
- Gemfile.lock
- test/controllers/test_categories_controller.rb
Required: https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/162
Added a test to test the parent category attribute of Category model, after making it accept multiple values.
> Feature: Add test for parent categories

- Gemfile
- Gemfile.lock
- helpers/users_helper.rb
- test/controllers/test_users_controller.rb
After Merging [PR#159](https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/159), `goo_attrs_to_load` doesn't load sensitive data, but we need it to reset the password so we explicitly load it.
> Fix: Broken password reset after merging (ontologies_linked_data PR#159) + Add User sensitive data unit test

- Gemfile.lock
- controllers/classes_controller.rb
fix https://github.com/lifewatch-eric/ecoportal_web_ui/issues/80 and require https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/166
> Fix: Class children not filtred by a scheme 

- helpers/users_helper.rb
Related to this https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/170
> Fix: explicitly load `resetTokenExpireTime` in password reset

- controllers/categories_controller.rb
- controllers/groups_controller.rb
- helpers/ontology_helper.rb
Fix for: https://github.com/ontoportal-lirmm/ontologies_api/issues/94
Reject showing private ontologies for non admin users when accessing `/groups`, `/groups/:acronym`, `/categories`, `/categories/:acronym`.
> Fix: hide private ontologies for non admin users in groups controller

- controllers/artefacts.rb
This pull request introduces the implementation of various routes for the MOD-API, enabling access to artefact and distribution data.
| **Route**   | **Description** | **Expected Result** | **HTTP Status Codes**  | **Parameters** |
|-------------------|-------------------------|-------------------------------|-------------------------------------|--------------------------|
| `GET /artefacts` | Retrieves a list of all artefacts. | A list of artefacts in JSON format. | `200 OK`,   `404 Not Found`  | `display`         |
| `GET /artefacts/:artefactID`                       | Retrieves details of a specific artefact.        | Artefact details in JSON format.            | `200 OK`, `404 Not Found`  | `display`                     |
| `GET /artefacts/:artefactID/distributions`         | Lists …
> Feature: Implement MOD-API routes

- .env.sample
The application was unable to connect to Redis due to missing environment variables specifying the Redis host. The API expected Redis connections for caching (GOO cache, HTTP cache) to be at localhost, this resulted in connection errors when trying to access Redis services.
> Fix: Configure GOO cache and HTTP cache to use `redis-ut` as hostname

- controllers/artefacts.rb
- see: https://github.com/ontoportal-lirmm/ontologies_api/issues/124
- https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/192
Activate the paging by default to /artefacts route
> Fix: add paging by default to /artefacts

- Dockerfile
see issue: https://github.com/ontoportal-lirmm/ontologies_api/issues/132
Solution it to remove the appuser as it's not doing anything and it's causing ownership errors when running bundle install with local code
> Fix: Remove appuser from the dockerfile

- Dockerfile
without pandoc we have this error
solution is just add pandoc installation in Dockerfile
> add pandoc so to render the documentation

- Dockerfile
- Without the file command installed in the docker image we will have problems when deleting ontologies because it's uses file command in ontologies_linked_data
- Deleting an ontology have this error because of this 
```
Errno::ENOENT: No such file or directory - file
/srv/ontoportal/ontologies_linked_data/lib/ontologies_linked_data/utils/file.rb:23:in ``'
/srv/ontoportal/ontologies_linked_data/lib/ontologies_linked_data/utils/file.rb:23:in `zip?'
/srv/ontoportal/ontologies_linked_data/lib/ontologies_linked_data/models/ontology_submission.rb:434:in `zipped?'
/srv/ontoportal/ontologies_linked_data/lib/ontologies_linked_data/services/submission_process/operations/submission_archiver.rb:41:in `zip_submission_uploaded_file'
/srv/ontoportal/ontologies_linked_data/lib/ontologies_linked_data/serv …
```
> Hotfix: add file command in dockerfile

- controllers/metrics_controller.rb
The `/metrics` controller is too slow without the cache. This PR address this issue and optimize the routes.
- When we call `/ontologies/STY/metrics` and we check the logs of 4store (triple store) we see a lot of sparql queries are executed
- The number of sparql queries executed (from Q2096 to Q2130) = 35 
- Check the full list of queries here: [List sparql queries (metrics)](https://www.notion.so/imadbourouche/Diagnosis-1b22388ee64580bba038fe31a5932cf8)
- With the new code we optimized a lot the number of sparql queries executed 
- The number of sparql queries executed (from Q2172 to Q2174) = 3
- Check the full list of queries after this change: [List sparql queries (metrics)](https://www.notion.so/imadbourouche/Diagnosis-1b22388ee64580bba038fe31a5932cf8)
|  criteria  | Before  | After …
> Feature: optimize metrics controller

- app.rb
the RewindableInput middleware is causing post request to not parse it's params from the body
> fix: remove Rack::RewindableInput Middleware causing post request to not work
